# Login Menu
LOGIN = "1"
QUIT = "2"

# Management
MODIFY_PASSWORD = "1"
USERS_MENU = "2"
CLIENTS_MENU = "3"
CONTRACTS_MENU = "4"
EVENTS_MENU = "5"

# Sales
MODIFY_PASSWORD = "1"
CLIENTS_MENU = "2"
CONTRACTS_MENU = "3"
EVENTS_MENU = "4"

# Support
MODIFY_PASSWORD = "1"
CLIENTS_MENU = "2"
CONTRACTS_MENU = "3"
EVENTS_MENU = "4"

# Users Menu
CREATE_USER = "1"
UPDATE_USER = "2"
DELETE_USER = "3"
VIEW_USER_LIST = "4"

# Clients Menu
CREATE_CLIENT = "1"
UPDATE_CLIENT = "2"
DELETE_CLIENT = "3"
VIEW_CLIENT_LIST = "4"

# Contracts Menu
CREATE_CONTRACT = "1"
UPDATE_CONTRACT = "2"
DELETE_CONTRACT = "3"
VIEW_CONTRACT_LIST = "4"

# Events Menu
CREATE_EVENT = "1"
UPDATE_EVENT = "2"
DELETE_EVENT = "3"
VIEW_EVENT_LIST = "4"
