# Login Menu
LOGIN = "1"
DISCONNECT = "2"

# Admin
# Admin Main Menu
ADMIN_VIEW_USERS = "1"
ADMIN_CREATE_USER = "2"
ADMIN_UPDATE_USER = "3"
ADMIN_DELETE_USER = "4"
ADMIN_CLIENTS_MENU = "5"
ADMIN_CONTRACTS_MENU = "6"
ADMIN_EVENTS_MENU = "7"

# Admin Clients
ADMIN_VIEW_CLIENT = "1"
ADMIN_UPDATE_CLIENT = "2"
ADMIN_DELETE_CLIENT = "3"

# Admin contracts
ADMIN_VIEW_CONTRACT = "1"
ADMIN_CREATE_CONTRACT = "2"
ADMIN_UPDATE_CONTRACT = "3"
ADMIN_DELETE_CONTRACT = "4"

# Admin events
ADMIN_VIEW_EVENT = "1"
ADMIN_CREATE_EVENT = "2"
ADMIN_UPDATE_EVENT = "3"
ADMIN_DELETE_EVENT = "4"


# Management
# Management Main Menu
MANAGEMENT_MODIFY_PASSWORD = "1"
MANAGEMENT_USERS_MENU = "2"
MANAGEMENT_CLIENTS_MENU = "3"
MANAGEMENT_CONTRACTS_MENU = "4"
MANAGEMENT_EVENTS_MENU = "5"

# Management User Menu
MANAGEMENT_VIEW_USERS = "1"
MANAGEMENT_CREATE_USER = "2"
MANAGEMENT_UPDATE_USER = "3"
MANAGEMENT_DELETE_USER = "4"

# Management Clients
MANAGEMENT_VIEW_CLIENT = "1"
MANAGEMENT_UPDATE_CLIENT_SALES = "2"

# Management contracts
MANAGEMENT_VIEW_CONTRACT = "1"
MANAGEMENT_CREATE_CONTRACT = "2"
MANAGEMENT_UPDATE_CONTRACT = "3"

# Management events
MANAGEMENT_VIEW_EVENT = "1"
MANAGEMENT_VIEW_NO_SUPPORT = "2"
MANAGEMENT_UPDATE_NO_SUPPORT = "3"

# Sales
# Sales Main Menu
SALES_MODIFY_PASSWORD = "1"
SALES_CLIENTS_MENU = "2"
SALES_CONTRACTS_MENU = "3"
SALES_EVENTS_MENU = "4"

# Sales Clients Menu
SALES_VIEW_CLIENT = "1"
SALES_CREATE_CLIENT = "2"
SALES_UPDATE_CLIENT = "3"
SALES_VIEW_OWN_CLIENT = "4"

# Sales contracts Menu
SALES_VIEW_CONTRACT = "1"
SALES_CREATE_CONTRACT = "2"
SALES_UPDATE_OWN_CONTRACT = "3"
SALES_UNSIGNED_CONTRACT = "4"
SALES_UNPAID_CONTRACT = "5"
SALES_VIEW_OWN_CONTRACT = "6"

# Sales events Menu
SALES_VIEW_EVENT = "1"
SALES_CREATE_EVENT = "2"

# Support
# Support Main Menu
SUPPORT_MODIFY_PASSWORD = "1"
SUPPORT_CLIENTS_MENU = "2"
SUPPORT_CONTRACTS_MENU = "3"
SUPPORT_EVENTS_MENU = "4"

# Support Clients Menu
SUPPORT_VIEW_CLIENT = "1"

# Support contracts Menu
SUPPORT_VIEW_CONTRACT = "1"

# Support events Menu
SUPPORT_VIEW_EVENT = "1"
SUPPORT_VIEW_OWN_EVENT = "2"
SUPPORT_UPDATE_EVENT = "3"

# User Update Menu
UPDATE_NAME = "1"
UPDATE_FIRSTNAME = "2"
UPDATE_EMAIL = "3"
UPDATE_PASSWORD = "4"

# Clients Update Menu
CLIENT_UPDATE_NAME = "1"
CLIENT_UPDATE_FIRSTNAME = "2"
CLIENT_UPDATE_EMAIL = "3"
CLIENT_UPDATE_PHONE = "4"
CLIENT_UPDATE_COMPANY = "5"
CLIENT_UPDATE_LAST_CONTACT = "6"


# Contract Update Menu
CONTRACT_UPDATE_CLIENT = "1"
CONTRACT_UPDATE_STATUS = "2"
CONTRACT_UPDATE_REMAIN = "3"
CONTRACT_UPDATE_SALES = "4"


# Events Update Menu
EVENT_UPDATE_START_DATE = "1"
EVENT_UPDATE_END_DATE = "2"
EVENT_UPDATE_LOCATION = "3"
EVENT_UPDATE_ATTENDEES = "4"
EVENT_UPDATE_NOTES = "5"
